/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_empleados;
import clases.cl_zona;
import java.awt.event.KeyEvent;
import models.cl_combobox;
import models.m_empleados;

/**
 *
 * @author CALIDAD
 */
public class frm_ver_zonas extends javax.swing.JInternalFrame {

    cl_zona c_zona = new cl_zona();
    cl_empleados c_empleado;

    m_empleados m_empleados = new m_empleados();
    String query;

    int fila = -1;

    /**
     * Creates new form frm_ver_marcas
     */
    public frm_ver_zonas() {
        initComponents();
        query = "select z.id_zona, z.nombre, z.ciudad, e.nick, e.ape_pat, e.ape_mat, e.nombres "
                + "from zona as z "
                + "inner join empleados as e on e.id_empleado = z.id_empleado "
                + "order by e.ape_pat, e.ape_mat, e.nombres, z.nombre asc";
        c_zona.ver_zonas(t_zonas, query);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_formulario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_frm_id = new javax.swing.JTextField();
        txt_frm_nombre = new javax.swing.JTextField();
        txt_frm_ciudad = new javax.swing.JTextField();
        cbx_frm_empleado = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btn_frm_grabar = new javax.swing.JButton();
        btn_frm_modificar = new javax.swing.JButton();
        btn_frm_salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_zonas = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txt_buscar = new javax.swing.JTextField();

        jLabel1.setText("Id Zona:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Empleado:");

        jLabel4.setText("Ciudad:");

        txt_frm_id.setEnabled(false);

        txt_frm_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_frm_nombreKeyPressed(evt);
            }
        });

        txt_frm_ciudad.setEnabled(false);
        txt_frm_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_frm_ciudadKeyPressed(evt);
            }
        });

        cbx_frm_empleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_frm_empleado.setEnabled(false);
        cbx_frm_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_frm_empleadoKeyPressed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setBorderPainted(false);

        btn_frm_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_frm_grabar.setText("Grabar");
        btn_frm_grabar.setEnabled(false);
        btn_frm_grabar.setFocusable(false);
        btn_frm_grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_frm_grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_frm_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frm_grabarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_frm_grabar);

        btn_frm_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/application_edit.png"))); // NOI18N
        btn_frm_modificar.setText("Modificar");
        btn_frm_modificar.setEnabled(false);
        btn_frm_modificar.setFocusable(false);
        btn_frm_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_frm_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_frm_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frm_modificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_frm_modificar);

        btn_frm_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btn_frm_salir.setText("Salir");
        btn_frm_salir.setFocusable(false);
        btn_frm_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_frm_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_frm_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_frm_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_frm_salir);

        javax.swing.GroupLayout jd_formularioLayout = new javax.swing.GroupLayout(jd_formulario.getContentPane());
        jd_formulario.getContentPane().setLayout(jd_formularioLayout);
        jd_formularioLayout.setHorizontalGroup(
            jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_formularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_frm_empleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jd_formularioLayout.createSequentialGroup()
                        .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_frm_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_frm_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_frm_id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_formularioLayout.setVerticalGroup(
            jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_formularioLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_frm_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_frm_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_frm_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_frm_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setTitle("Ver Zonas ");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        t_zonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_zonas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        t_zonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_zonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_zonas);

        jToolBar2.setFloatable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/application_edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_modificar);
        jToolBar2.add(jSeparator2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);
        jToolBar2.add(jSeparator1);

        jLabel6.setText("Ayuda:   Presione enter para buscar");
        jToolBar2.add(jLabel6);

        jLabel5.setText("Buscar por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDEDOR", "ZONA", "CIUDAD" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_formulario.setSize(579, 240);
        jd_formulario.setModal(true);
        jd_formulario.setLocationRelativeTo(null);
        m_empleados.llenar_combobox(cbx_frm_empleado);
        txt_frm_nombre.requestFocus();
        jd_formulario.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_frm_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frm_salirActionPerformed
        jd_formulario.dispose();
    }//GEN-LAST:event_btn_frm_salirActionPerformed

    private void txt_frm_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_frm_nombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_frm_nombre.getText().length() > 0) {
                txt_frm_ciudad.setEnabled(true);
                txt_frm_ciudad.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_frm_nombreKeyPressed

    private void txt_frm_ciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_frm_ciudadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_frm_ciudad.getText().length() > 0) {
                cbx_frm_empleado.setEnabled(true);
                cbx_frm_empleado.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_frm_ciudadKeyPressed

    private void cbx_frm_empleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_frm_empleadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_frm_grabar.setEnabled(true);
            btn_frm_grabar.requestFocus();
        }
    }//GEN-LAST:event_cbx_frm_empleadoKeyPressed

    private void limpiar() {
        txt_frm_nombre.setText("");
        txt_frm_ciudad.setText("");
        txt_frm_id.setText("");
        txt_frm_ciudad.setEnabled(false);
        cbx_frm_empleado.setEnabled(false);
        btn_frm_grabar.setEnabled(false);
    }

    private void btn_frm_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frm_grabarActionPerformed
        //
        c_zona.setNombre(txt_frm_nombre.getText());
        c_zona.setCiudad(txt_frm_ciudad.getText());

        cl_combobox c_combo = (cl_combobox) cbx_frm_empleado.getSelectedItem();
        c_zona.setId_empleado(c_combo.getId());

        c_zona.obtener_id();

        if (c_zona.insertar()) {
            c_zona.ver_zonas(t_zonas, query);
            limpiar();
            jd_formulario.dispose();
        }


    }//GEN-LAST:event_btn_frm_grabarActionPerformed

    private void t_zonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_zonasMouseClicked
        // TODO add your handling code here:
        fila = t_zonas.getSelectedRow();
        btn_modificar.setEnabled(true);


    }//GEN-LAST:event_t_zonasMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (fila > -1) {
            btn_modificar.setEnabled(false);

            c_zona.setId_zona(Integer.parseInt(t_zonas.getValueAt(fila, 0).toString()));
            c_zona.cargar_datos();

            txt_frm_id.setText(c_zona.getId_zona() + "");
            txt_frm_nombre.setText(c_zona.getNombre());
            txt_frm_ciudad.setText(c_zona.getCiudad());

            c_empleado = new cl_empleados();
            c_empleado.setId_empleado(c_zona.getId_empleado());
            c_empleado.cargar_datos();

            txt_frm_ciudad.setEnabled(true);
            cbx_frm_empleado.setEnabled(true);

            String nom_empleado = c_empleado.getApe_pat() + " " + c_empleado.getApe_mat() + " " + c_empleado.getNombres();
            cbx_frm_empleado.getModel().setSelectedItem(new cl_combobox(c_empleado.getId_empleado(), nom_empleado));

            jd_formulario.setSize(579, 240);
            jd_formulario.setModal(true);
            jd_formulario.setLocationRelativeTo(null);

            txt_frm_nombre.requestFocus();
            jd_formulario.setVisible(true);
            btn_frm_modificar.setEnabled(true);
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_frm_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_frm_modificarActionPerformed
        c_zona.setNombre(txt_frm_nombre.getText());
        c_zona.setCiudad(txt_frm_ciudad.getText());

        cl_combobox c_combo = (cl_combobox) cbx_frm_empleado.getSelectedItem();
        c_zona.setId_empleado(c_combo.getId());

        if (c_zona.modificar()) {
            c_zona.ver_zonas(t_zonas, query);
            limpiar();
            jd_formulario.dispose();
        }

    }//GEN-LAST:event_btn_frm_modificarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        txt_buscar.setText("");
        txt_buscar.requestFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_buscar.setText("");
            txt_buscar.requestFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void txt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_buscar.getText();
            int tipo_busqueda = jComboBox1.getSelectedIndex();
            if (tipo_busqueda == 0) {
                query = "select z.id_zona, z.nombre, z.ciudad, e.nick, e.ape_pat, e.ape_mat, e.nombres "
                        + "from zona as z "
                        + "inner join empleados as e on e.id_empleado = z.id_empleado "
                        + "where concat(e.ape_pat, ' ',e.ape_mat, ' ', e.nombres) like '%" + texto + "%' "
                        + "order by e.ape_pat, e.ape_mat, e.nombres, z.nombre asc";

            }
            if (tipo_busqueda == 1) {
                query = "select z.id_zona, z.nombre, z.ciudad, e.nick, e.ape_pat, e.ape_mat, e.nombres "
                        + "from zona as z "
                        + "inner join empleados as e on e.id_empleado = z.id_empleado "
                        + "where nombre like '%" + texto + "%' "
                        + "order by e.ape_pat, e.ape_mat, e.nombres, z.nombre asc";

            }
            if (tipo_busqueda == 2) {
                query = "select z.id_zona, z.nombre, z.ciudad, e.nick, e.ape_pat, e.ape_mat, e.nombres "
                        + "from zona as z "
                        + "inner join empleados as e on e.id_empleado = z.id_empleado "
                        + "where ciudad like '%" + texto + "%' "
                        + "order by e.ape_pat, e.ape_mat, e.nombres, z.nombre asc";

            }
            c_zona.ver_zonas(t_zonas, query);
        }
    }//GEN-LAST:event_txt_buscarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_frm_grabar;
    private javax.swing.JButton btn_frm_modificar;
    private javax.swing.JButton btn_frm_salir;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cbx_frm_empleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JDialog jd_formulario;
    private javax.swing.JTable t_zonas;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_frm_ciudad;
    private javax.swing.JTextField txt_frm_id;
    private javax.swing.JTextField txt_frm_nombre;
    // End of variables declaration//GEN-END:variables
}
